// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVfjzBNoE_1zKzwyVKJanGMMXjgONb2sI',
    appId: '1:255260437042:web:6305ce7b04f5cb4bbd6a2b',
    messagingSenderId: '255260437042',
    projectId: 'quizzyaoo',
    authDomain: 'quizzyaoo.firebaseapp.com',
    storageBucket: 'quizzyaoo.firebasestorage.app',
    measurementId: 'G-ZJZS5MF06B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRztmfey2txPDs5V_3xVzPswaGDYjj1pk',
    appId: '1:255260437042:android:e42536d2be7a0f46bd6a2b',
    messagingSenderId: '255260437042',
    projectId: 'quizzyaoo',
    storageBucket: 'quizzyaoo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg3bSv6rnte4pefNzEfmFytZ9lu3nmIE4',
    appId: '1:255260437042:ios:e05be7374f04a68ebd6a2b',
    messagingSenderId: '255260437042',
    projectId: 'quizzyaoo',
    storageBucket: 'quizzyaoo.firebasestorage.app',
    iosBundleId: 'com.example.quizzy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg3bSv6rnte4pefNzEfmFytZ9lu3nmIE4',
    appId: '1:255260437042:ios:e05be7374f04a68ebd6a2b',
    messagingSenderId: '255260437042',
    projectId: 'quizzyaoo',
    storageBucket: 'quizzyaoo.firebasestorage.app',
    iosBundleId: 'com.example.quizzy',
  );
}
