final List<Map<String, dynamic>> categories = [
  {
    'id': 'cat-art',
    'name': 'Art',
    'description': 'Creativity, painting, design and more',
    'icon': 'palette',
    'gradientStart': '#6F5DF5',
    'gradientEnd': '#9B6BFF',
    'kahootCount': 24,
  },
  {
    'id': 'cat-science',
    'name': 'Science',
    'description': 'Physics, biology and discoveries',
    'icon': 'science',
    'gradientStart': '#43CEA2',
    'gradientEnd': '#185A9D',
    'kahootCount': 32,
  },
  {
    'id': 'cat-history',
    'name': 'History',
    'description': 'Ancient worlds and modern events',
    'icon': 'history_edu',
    'gradientStart': '#F3904F',
    'gradientEnd': '#3B4371',
    'kahootCount': 18,
  },
  {
    'id': 'cat-sports',
    'name': 'Sports',
    'description': 'Matches, athletes and records',
    'icon': 'sports_soccer',
    'gradientStart': '#11998E',
    'gradientEnd': '#38EF7D',
    'kahootCount': 21,
  },
];

final List<Map<String, dynamic>> seedKahoots = [
  {
    'id': 'kh-planet-earth',
    'title': 'Planet Earth Trivia',
    'description': 'Quick quiz about our planet and ecosystems.',
    'coverImageId': 'https://images.unsplash.com/photo-1451188502541-13943edb6acb?auto=format&fit=crop&w=900&q=60',
    'visibility': 'public',
    'themeId': 'theme-default-001',
    'authorId': 'author-demo-001',
    'category': 'Science',
    'status': 'publish',
    'createdAt': '2024-11-20T10:00:00.000Z',
    'playCount': 152,
    'questions': [
      {
        'id': 'q-earth-1',
        'text': 'What gas do plants primarily absorb for photosynthesis?',
        'type': 'quiz',
        'timeLimit': 20,
        'points': 1000,
        'answers': [
          {'id': 'a1', 'text': 'Carbon dioxide', 'isCorrect': true},
          {'id': 'a2', 'text': 'Oxygen', 'isCorrect': false},
          {'id': 'a3', 'text': 'Nitrogen', 'isCorrect': false},
          {'id': 'a4', 'text': 'Hydrogen', 'isCorrect': false},
        ],
      },
      {
        'id': 'q-earth-2',
        'text': 'True or False: The Amazon is the largest rainforest on Earth.',
        'type': 'trueFalse',
        'timeLimit': 15,
        'points': 500,
        'answers': [
          {'id': 'a5', 'text': 'True', 'isCorrect': true},
          {'id': 'a6', 'text': 'False', 'isCorrect': false},
        ],
      },
    ],
  },
  {
    'id': 'kh-world-history',
    'title': 'World History Highlights',
    'description': 'Milestones that changed the world.',
    'coverImageId': 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=60',
    'visibility': 'public',
    'themeId': 'theme-default-001',
    'authorId': 'author-demo-001',
    'category': 'History',
    'status': 'publish',
    'createdAt': '2024-11-10T08:30:00.000Z',
    'playCount': 98,
    'questions': [
      {
        'id': 'q-history-1',
        'text': 'Who was the first emperor of Rome?',
        'type': 'quiz',
        'timeLimit': 20,
        'points': 1000,
        'answers': [
          {'id': 'a1', 'text': 'Augustus', 'isCorrect': true},
          {'id': 'a2', 'text': 'Julius Caesar', 'isCorrect': false},
          {'id': 'a3', 'text': 'Nero', 'isCorrect': false},
          {'id': 'a4', 'text': 'Tiberius', 'isCorrect': false},
        ],
      },
      {
        'id': 'q-history-2',
        'text': 'Short answer: In which year did the Berlin Wall fall?',
        'type': 'shortAnswer',
        'timeLimit': 25,
        'points': 1000,
        'answers': [],
      },
    ],
  },
  {
    'id': 'kh-sports-legends',
    'title': 'Sports Legends',
    'description': 'Iconic moments and athletes.',
    'coverImageId': 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=900&q=60',
    'visibility': 'public',
    'themeId': 'theme-default-001',
    'authorId': 'author-demo-001',
    'category': 'Sports',
    'status': 'publish',
    'createdAt': '2024-11-05T09:45:00.000Z',
    'playCount': 45,
    'questions': [
      {
        'id': 'q-sports-1',
        'text': 'Which country has won the most FIFA World Cups?',
        'type': 'quiz',
        'timeLimit': 20,
        'points': 1000,
        'answers': [
          {'id': 'a1', 'text': 'Brazil', 'isCorrect': true},
          {'id': 'a2', 'text': 'Germany', 'isCorrect': false},
          {'id': 'a3', 'text': 'Italy', 'isCorrect': false},
          {'id': 'a4', 'text': 'Argentina', 'isCorrect': false},
        ],
      },
    ],
  },
];
